[phases.setup]
  nixPkgs = ["nodejs_20", "pnpm-8_x", "bun"]

[phases.install]
  cmds = [
    "pnpm install --prod"
  ]

[phases.build]
  cmds = [
    "pnpm run build"
  ]

[phases.start]
  cmd = [
    "pnpm run start"
  ]