[phases.setup]
  nixPkgs = ["nodejs_22"]

[phases.install]
  cmds = [
    "bun install --production"
  ]

[phases.build]
  cmds = [
    "bun run build"
  ]

[phases.start]
  cmd = [
    "bun run start"
  ]