[variables]
  BUN_INSTALL = "/root/.bun"
  PATH = "/root/.bun/bin:${PATH}"

[phases.setup]
  nixPkgs = ["nodejs_22", "unzip"]
  cmds = ["curl -fsSL https://bun.sh/install | bash -s 'bun-v1.3.2'"]

[phases.install]
  cmds = [
    "bun install --production"
  ]

[phases.build]
  cmds = [
    "bun run build"
  ]

[phases.start]
  cmd = [
    "bun run start"
  ]