import { $ } from "bun"
import { resolve } from "node:path"

const projectId = process.env.NEON_PROJECT_ID

if (!projectId) {
  console.error("Set NEON_PROJECT_ID in .env")
  process.exit(1)
}

const branchName = process.env.NEON_DEV_BRANCH_NAME ?? "jrnxf"

console.log(`Deleting existing dev branch '${branchName}' (if it exists)...`)
await $`neonctl branches delete ${branchName} --project-id ${projectId}`
  .quiet()
  .nothrow()

console.log(`Creating fresh branch '${branchName}' from main...`)
const branchJson =
  await $`neonctl branches create --project-id ${projectId} --name ${branchName} --parent main --output json`
    .quiet()
    .text()
const branchId = (JSON.parse(branchJson) as { branch: { id: string } }).branch
  .id

const connectionString =
  await $`neonctl connection-string --project-id ${projectId} --branch ${branchName}`.text()

const trimmed = connectionString.trim()
const url = new URL(trimmed)

const dbVars: Record<string, string> = {
  DATABASE_URL: trimmed,
  DATABASE_HOST: url.hostname,
  DATABASE_NAME: url.pathname.slice(1),
  DATABASE_USER: url.username,
  DATABASE_PASSWORD: decodeURIComponent(url.password),
}

// Update .env — remove existing DATABASE_* lines and append fresh ones
const envPath = resolve(import.meta.dirname, "../../.env")
const envFile = Bun.file(envPath)
let lines: string[] = (await envFile.text()).split("\n")

// Remove existing DATABASE_* lines and their comment header
lines = lines.filter(
  (line) =>
    !line.match(/^DATABASE_(URL|HOST|NAME|USER|PASSWORD)=/) &&
    !line.match(/^# neon .+ branch .+ — auto-generated by/),
)

// Remove trailing blank lines so we get a clean append
while (lines.length > 0 && lines.at(-1).trim() === "") {
  lines.pop()
}

// Append new DATABASE_* vars with comment header
lines.push("")
lines.push(
  `# neon ${branchName} branch (${branchId}) — auto-generated by \`bun run db:reset-dev\``,
)
for (const [key, value] of Object.entries(dbVars)) {
  lines.push(`${key}=${value}`)
}
lines.push("")

await Bun.write(envPath, lines.join("\n"))

console.log("")
console.log("Done! Your dev branch is ready.")
console.log(`Updated ${envPath} with new DATABASE_* values.`)
