/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultIndexRouteImport } from './routes/vault/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TricksIndexRouteImport } from './routes/tricks/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as TricksTrickIdRouteImport } from './routes/tricks/$trickId'
import { Route as StatsContributorsRouteImport } from './routes/stats/contributors'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthedFeedbackRouteImport } from './routes/_authed/feedback'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as GamesSiusRouteRouteImport } from './routes/games/sius/route'
import { Route as GamesRiusRouteRouteImport } from './routes/games/rius/route'
import { Route as GamesBiusRouteRouteImport } from './routes/games/bius/route'
import { Route as VaultVideoIdIndexRouteImport } from './routes/vault/$videoId/index'
import { Route as PostsPostIdIndexRouteImport } from './routes/posts/$postId/index'
import { Route as GamesSiusIndexRouteImport } from './routes/games/sius/index'
import { Route as GamesBiusIndexRouteImport } from './routes/games/bius/index'
import { Route as AuthedNotificationsIndexRouteImport } from './routes/_authed/notifications/index'
import { Route as VaultValutBakRouteImport } from './routes/vault/valut.bak'
import { Route as GamesSiusStartRouteImport } from './routes/games/sius/start'
import { Route as GamesRiusActiveRouteImport } from './routes/games/rius/active'
import { Route as GamesBiusStartRouteImport } from './routes/games/bius/start'
import { Route as AuthCodeVerifyRouteImport } from './routes/auth/code/verify'
import { Route as AuthCodeSendRouteImport } from './routes/auth/code/send'
import { Route as ApiMuxWebhookRouteImport } from './routes/api/mux/webhook'
import { Route as AuthedTricksSubmitRouteImport } from './routes/_authed/tricks/submit'
import { Route as AuthedTricksReviewRouteImport } from './routes/_authed/tricks/review'
import { Route as AuthedPostsCreateRouteImport } from './routes/_authed/posts/create'
import { Route as AuthedNotificationsSettingsRouteImport } from './routes/_authed/notifications/settings'
import { Route as GamesRiusUpcomingIndexRouteImport } from './routes/games/rius/upcoming/index'
import { Route as GamesRiusPreviousIndexRouteImport } from './routes/games/rius/previous/index'
import { Route as AuthedAuthMeIndexRouteImport } from './routes/_authed/auth/me/index'
import { Route as AuthedTricksTrickIdSuggestRouteImport } from './routes/_authed/tricks/$trickId/suggest'
import { Route as AuthedTricksTrickIdSubmitVideoRouteImport } from './routes/_authed/tricks/$trickId/submit-video'
import { Route as AuthedPostsPostIdEditRouteImport } from './routes/_authed/posts/$postId/edit'
import { Route as AuthedAuthMeEditRouteImport } from './routes/_authed/auth/me/edit'
import { Route as AuthedAdminTricksModifiersRouteImport } from './routes/_authed/admin/tricks/modifiers'
import { Route as AuthedAdminTricksCreateRouteImport } from './routes/_authed/admin/tricks/create'
import { Route as GamesSiusStacksStackIdIndexRouteImport } from './routes/games/sius/stacks/$stackId/index'
import { Route as GamesRiusSubmissionsSubmissionIdIndexRouteImport } from './routes/games/rius/submissions/$submissionId/index'
import { Route as GamesRiusSetsSetIdIndexRouteImport } from './routes/games/rius/sets/$setId/index'
import { Route as GamesBiusSetsSetIdIndexRouteImport } from './routes/games/bius/sets/$setId/index'
import { Route as AuthedTricksSuggestionsSuggestionIdIndexRouteImport } from './routes/_authed/tricks/suggestions/$suggestionId/index'
import { Route as AuthedTricksSubmissionsSubmissionIdIndexRouteImport } from './routes/_authed/tricks/submissions/$submissionId/index'
import { Route as AuthedAdminTricksElementsIndexRouteImport } from './routes/_authed/admin/tricks/elements/index'
import { Route as AuthedGamesRiusUpcomingJoinRouteImport } from './routes/_authed/games/rius/upcoming/join'
import { Route as AuthedAdminTricksElementsCreateRouteImport } from './routes/_authed/admin/tricks/elements/create'
import { Route as AuthedAdminTricksTrickIdVideosRouteImport } from './routes/_authed/admin/tricks/$trickId/videos'
import { Route as AuthedAdminTricksTrickIdEditRouteImport } from './routes/_authed/admin/tricks/$trickId/edit'
import { Route as AuthedAdminTricksElementsElementIdEditRouteImport } from './routes/_authed/admin/tricks/elements/$elementId/edit'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/vault/',
  path: '/vault/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TricksIndexRoute = TricksIndexRouteImport.update({
  id: '/tricks/',
  path: '/tricks/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const TricksTrickIdRoute = TricksTrickIdRouteImport.update({
  id: '/tricks/$trickId',
  path: '/tricks/$trickId',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsContributorsRoute = StatsContributorsRouteImport.update({
  id: '/stats/contributors',
  path: '/stats/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedFeedbackRoute = AuthedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const GamesSiusRouteRoute = GamesSiusRouteRouteImport.update({
  id: '/games/sius',
  path: '/games/sius',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRiusRouteRoute = GamesRiusRouteRouteImport.update({
  id: '/games/rius',
  path: '/games/rius',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesBiusRouteRoute = GamesBiusRouteRouteImport.update({
  id: '/games/bius',
  path: '/games/bius',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultVideoIdIndexRoute = VaultVideoIdIndexRouteImport.update({
  id: '/vault/$videoId/',
  path: '/vault/$videoId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdIndexRoute = PostsPostIdIndexRouteImport.update({
  id: '/posts/$postId/',
  path: '/posts/$postId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSiusIndexRoute = GamesSiusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesSiusRouteRoute,
} as any)
const GamesBiusIndexRoute = GamesBiusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesBiusRouteRoute,
} as any)
const AuthedNotificationsIndexRoute =
  AuthedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthedRoute,
  } as any)
const VaultValutBakRoute = VaultValutBakRouteImport.update({
  id: '/vault/valut/bak',
  path: '/vault/valut/bak',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSiusStartRoute = GamesSiusStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => GamesSiusRouteRoute,
} as any)
const GamesRiusActiveRoute = GamesRiusActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => GamesRiusRouteRoute,
} as any)
const GamesBiusStartRoute = GamesBiusStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => GamesBiusRouteRoute,
} as any)
const AuthCodeVerifyRoute = AuthCodeVerifyRouteImport.update({
  id: '/auth/code/verify',
  path: '/auth/code/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCodeSendRoute = AuthCodeSendRouteImport.update({
  id: '/auth/code/send',
  path: '/auth/code/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMuxWebhookRoute = ApiMuxWebhookRouteImport.update({
  id: '/api/mux/webhook',
  path: '/api/mux/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTricksSubmitRoute = AuthedTricksSubmitRouteImport.update({
  id: '/tricks/submit',
  path: '/tricks/submit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTricksReviewRoute = AuthedTricksReviewRouteImport.update({
  id: '/tricks/review',
  path: '/tricks/review',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsCreateRoute = AuthedPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsSettingsRoute =
  AuthedNotificationsSettingsRouteImport.update({
    id: '/notifications/settings',
    path: '/notifications/settings',
    getParentRoute: () => AuthedRoute,
  } as any)
const GamesRiusUpcomingIndexRoute = GamesRiusUpcomingIndexRouteImport.update({
  id: '/upcoming/',
  path: '/upcoming/',
  getParentRoute: () => GamesRiusRouteRoute,
} as any)
const GamesRiusPreviousIndexRoute = GamesRiusPreviousIndexRouteImport.update({
  id: '/previous/',
  path: '/previous/',
  getParentRoute: () => GamesRiusRouteRoute,
} as any)
const AuthedAuthMeIndexRoute = AuthedAuthMeIndexRouteImport.update({
  id: '/auth/me/',
  path: '/auth/me/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTricksTrickIdSuggestRoute =
  AuthedTricksTrickIdSuggestRouteImport.update({
    id: '/tricks/$trickId/suggest',
    path: '/tricks/$trickId/suggest',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTricksTrickIdSubmitVideoRoute =
  AuthedTricksTrickIdSubmitVideoRouteImport.update({
    id: '/tricks/$trickId/submit-video',
    path: '/tricks/$trickId/submit-video',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPostsPostIdEditRoute = AuthedPostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuthMeEditRoute = AuthedAuthMeEditRouteImport.update({
  id: '/auth/me/edit',
  path: '/auth/me/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminTricksModifiersRoute =
  AuthedAdminTricksModifiersRouteImport.update({
    id: '/tricks/modifiers',
    path: '/tricks/modifiers',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminTricksCreateRoute = AuthedAdminTricksCreateRouteImport.update({
  id: '/tricks/create',
  path: '/tricks/create',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const GamesSiusStacksStackIdIndexRoute =
  GamesSiusStacksStackIdIndexRouteImport.update({
    id: '/stacks/$stackId/',
    path: '/stacks/$stackId/',
    getParentRoute: () => GamesSiusRouteRoute,
  } as any)
const GamesRiusSubmissionsSubmissionIdIndexRoute =
  GamesRiusSubmissionsSubmissionIdIndexRouteImport.update({
    id: '/submissions/$submissionId/',
    path: '/submissions/$submissionId/',
    getParentRoute: () => GamesRiusRouteRoute,
  } as any)
const GamesRiusSetsSetIdIndexRoute = GamesRiusSetsSetIdIndexRouteImport.update({
  id: '/sets/$setId/',
  path: '/sets/$setId/',
  getParentRoute: () => GamesRiusRouteRoute,
} as any)
const GamesBiusSetsSetIdIndexRoute = GamesBiusSetsSetIdIndexRouteImport.update({
  id: '/sets/$setId/',
  path: '/sets/$setId/',
  getParentRoute: () => GamesBiusRouteRoute,
} as any)
const AuthedTricksSuggestionsSuggestionIdIndexRoute =
  AuthedTricksSuggestionsSuggestionIdIndexRouteImport.update({
    id: '/tricks/suggestions/$suggestionId/',
    path: '/tricks/suggestions/$suggestionId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTricksSubmissionsSubmissionIdIndexRoute =
  AuthedTricksSubmissionsSubmissionIdIndexRouteImport.update({
    id: '/tricks/submissions/$submissionId/',
    path: '/tricks/submissions/$submissionId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminTricksElementsIndexRoute =
  AuthedAdminTricksElementsIndexRouteImport.update({
    id: '/tricks/elements/',
    path: '/tricks/elements/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedGamesRiusUpcomingJoinRoute =
  AuthedGamesRiusUpcomingJoinRouteImport.update({
    id: '/games/rius/upcoming/join',
    path: '/games/rius/upcoming/join',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminTricksElementsCreateRoute =
  AuthedAdminTricksElementsCreateRouteImport.update({
    id: '/tricks/elements/create',
    path: '/tricks/elements/create',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminTricksTrickIdVideosRoute =
  AuthedAdminTricksTrickIdVideosRouteImport.update({
    id: '/tricks/$trickId/videos',
    path: '/tricks/$trickId/videos',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminTricksTrickIdEditRoute =
  AuthedAdminTricksTrickIdEditRouteImport.update({
    id: '/tricks/$trickId/edit',
    path: '/tricks/$trickId/edit',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminTricksElementsElementIdEditRoute =
  AuthedAdminTricksElementsElementIdEditRouteImport.update({
    id: '/tricks/elements/$elementId/edit',
    path: '/tricks/elements/$elementId/edit',
    getParentRoute: () => AuthedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/bius': typeof GamesBiusRouteRouteWithChildren
  '/games/rius': typeof GamesRiusRouteRouteWithChildren
  '/games/sius': typeof GamesSiusRouteRouteWithChildren
  '/admin': typeof AuthedAdminRouteWithChildren
  '/feedback': typeof AuthedFeedbackRoute
  '/auth/register': typeof AuthRegisterRoute
  '/stats/contributors': typeof StatsContributorsRoute
  '/tricks/$trickId': typeof TricksTrickIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/chat': typeof ChatIndexRoute
  '/games': typeof GamesIndexRoute
  '/map': typeof MapIndexRoute
  '/posts': typeof PostsIndexRoute
  '/stats': typeof StatsIndexRoute
  '/tricks': typeof TricksIndexRoute
  '/users': typeof UsersIndexRoute
  '/vault': typeof VaultIndexRoute
  '/notifications/settings': typeof AuthedNotificationsSettingsRoute
  '/posts/create': typeof AuthedPostsCreateRoute
  '/tricks/review': typeof AuthedTricksReviewRoute
  '/tricks/submit': typeof AuthedTricksSubmitRoute
  '/api/mux/webhook': typeof ApiMuxWebhookRoute
  '/auth/code/send': typeof AuthCodeSendRoute
  '/auth/code/verify': typeof AuthCodeVerifyRoute
  '/games/bius/start': typeof GamesBiusStartRoute
  '/games/rius/active': typeof GamesRiusActiveRoute
  '/games/sius/start': typeof GamesSiusStartRoute
  '/vault/valut/bak': typeof VaultValutBakRoute
  '/notifications': typeof AuthedNotificationsIndexRoute
  '/games/bius/': typeof GamesBiusIndexRoute
  '/games/sius/': typeof GamesSiusIndexRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
  '/vault/$videoId': typeof VaultVideoIdIndexRoute
  '/admin/tricks/create': typeof AuthedAdminTricksCreateRoute
  '/admin/tricks/modifiers': typeof AuthedAdminTricksModifiersRoute
  '/auth/me/edit': typeof AuthedAuthMeEditRoute
  '/posts/$postId/edit': typeof AuthedPostsPostIdEditRoute
  '/tricks/$trickId/submit-video': typeof AuthedTricksTrickIdSubmitVideoRoute
  '/tricks/$trickId/suggest': typeof AuthedTricksTrickIdSuggestRoute
  '/auth/me': typeof AuthedAuthMeIndexRoute
  '/games/rius/previous': typeof GamesRiusPreviousIndexRoute
  '/games/rius/upcoming': typeof GamesRiusUpcomingIndexRoute
  '/admin/tricks/$trickId/edit': typeof AuthedAdminTricksTrickIdEditRoute
  '/admin/tricks/$trickId/videos': typeof AuthedAdminTricksTrickIdVideosRoute
  '/admin/tricks/elements/create': typeof AuthedAdminTricksElementsCreateRoute
  '/games/rius/upcoming/join': typeof AuthedGamesRiusUpcomingJoinRoute
  '/admin/tricks/elements': typeof AuthedAdminTricksElementsIndexRoute
  '/tricks/submissions/$submissionId': typeof AuthedTricksSubmissionsSubmissionIdIndexRoute
  '/tricks/suggestions/$suggestionId': typeof AuthedTricksSuggestionsSuggestionIdIndexRoute
  '/games/bius/sets/$setId': typeof GamesBiusSetsSetIdIndexRoute
  '/games/rius/sets/$setId': typeof GamesRiusSetsSetIdIndexRoute
  '/games/rius/submissions/$submissionId': typeof GamesRiusSubmissionsSubmissionIdIndexRoute
  '/games/sius/stacks/$stackId': typeof GamesSiusStacksStackIdIndexRoute
  '/admin/tricks/elements/$elementId/edit': typeof AuthedAdminTricksElementsElementIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/rius': typeof GamesRiusRouteRouteWithChildren
  '/admin': typeof AuthedAdminRouteWithChildren
  '/feedback': typeof AuthedFeedbackRoute
  '/auth/register': typeof AuthRegisterRoute
  '/stats/contributors': typeof StatsContributorsRoute
  '/tricks/$trickId': typeof TricksTrickIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/chat': typeof ChatIndexRoute
  '/games': typeof GamesIndexRoute
  '/map': typeof MapIndexRoute
  '/posts': typeof PostsIndexRoute
  '/stats': typeof StatsIndexRoute
  '/tricks': typeof TricksIndexRoute
  '/users': typeof UsersIndexRoute
  '/vault': typeof VaultIndexRoute
  '/notifications/settings': typeof AuthedNotificationsSettingsRoute
  '/posts/create': typeof AuthedPostsCreateRoute
  '/tricks/review': typeof AuthedTricksReviewRoute
  '/tricks/submit': typeof AuthedTricksSubmitRoute
  '/api/mux/webhook': typeof ApiMuxWebhookRoute
  '/auth/code/send': typeof AuthCodeSendRoute
  '/auth/code/verify': typeof AuthCodeVerifyRoute
  '/games/bius/start': typeof GamesBiusStartRoute
  '/games/rius/active': typeof GamesRiusActiveRoute
  '/games/sius/start': typeof GamesSiusStartRoute
  '/vault/valut/bak': typeof VaultValutBakRoute
  '/notifications': typeof AuthedNotificationsIndexRoute
  '/games/bius': typeof GamesBiusIndexRoute
  '/games/sius': typeof GamesSiusIndexRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
  '/vault/$videoId': typeof VaultVideoIdIndexRoute
  '/admin/tricks/create': typeof AuthedAdminTricksCreateRoute
  '/admin/tricks/modifiers': typeof AuthedAdminTricksModifiersRoute
  '/auth/me/edit': typeof AuthedAuthMeEditRoute
  '/posts/$postId/edit': typeof AuthedPostsPostIdEditRoute
  '/tricks/$trickId/submit-video': typeof AuthedTricksTrickIdSubmitVideoRoute
  '/tricks/$trickId/suggest': typeof AuthedTricksTrickIdSuggestRoute
  '/auth/me': typeof AuthedAuthMeIndexRoute
  '/games/rius/previous': typeof GamesRiusPreviousIndexRoute
  '/games/rius/upcoming': typeof GamesRiusUpcomingIndexRoute
  '/admin/tricks/$trickId/edit': typeof AuthedAdminTricksTrickIdEditRoute
  '/admin/tricks/$trickId/videos': typeof AuthedAdminTricksTrickIdVideosRoute
  '/admin/tricks/elements/create': typeof AuthedAdminTricksElementsCreateRoute
  '/games/rius/upcoming/join': typeof AuthedGamesRiusUpcomingJoinRoute
  '/admin/tricks/elements': typeof AuthedAdminTricksElementsIndexRoute
  '/tricks/submissions/$submissionId': typeof AuthedTricksSubmissionsSubmissionIdIndexRoute
  '/tricks/suggestions/$suggestionId': typeof AuthedTricksSuggestionsSuggestionIdIndexRoute
  '/games/bius/sets/$setId': typeof GamesBiusSetsSetIdIndexRoute
  '/games/rius/sets/$setId': typeof GamesRiusSetsSetIdIndexRoute
  '/games/rius/submissions/$submissionId': typeof GamesRiusSubmissionsSubmissionIdIndexRoute
  '/games/sius/stacks/$stackId': typeof GamesSiusStacksStackIdIndexRoute
  '/admin/tricks/elements/$elementId/edit': typeof AuthedAdminTricksElementsElementIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/games/bius': typeof GamesBiusRouteRouteWithChildren
  '/games/rius': typeof GamesRiusRouteRouteWithChildren
  '/games/sius': typeof GamesSiusRouteRouteWithChildren
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/feedback': typeof AuthedFeedbackRoute
  '/auth/register': typeof AuthRegisterRoute
  '/stats/contributors': typeof StatsContributorsRoute
  '/tricks/$trickId': typeof TricksTrickIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/chat/': typeof ChatIndexRoute
  '/games/': typeof GamesIndexRoute
  '/map/': typeof MapIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/tricks/': typeof TricksIndexRoute
  '/users/': typeof UsersIndexRoute
  '/vault/': typeof VaultIndexRoute
  '/_authed/notifications/settings': typeof AuthedNotificationsSettingsRoute
  '/_authed/posts/create': typeof AuthedPostsCreateRoute
  '/_authed/tricks/review': typeof AuthedTricksReviewRoute
  '/_authed/tricks/submit': typeof AuthedTricksSubmitRoute
  '/api/mux/webhook': typeof ApiMuxWebhookRoute
  '/auth/code/send': typeof AuthCodeSendRoute
  '/auth/code/verify': typeof AuthCodeVerifyRoute
  '/games/bius/start': typeof GamesBiusStartRoute
  '/games/rius/active': typeof GamesRiusActiveRoute
  '/games/sius/start': typeof GamesSiusStartRoute
  '/vault/valut/bak': typeof VaultValutBakRoute
  '/_authed/notifications/': typeof AuthedNotificationsIndexRoute
  '/games/bius/': typeof GamesBiusIndexRoute
  '/games/sius/': typeof GamesSiusIndexRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
  '/vault/$videoId/': typeof VaultVideoIdIndexRoute
  '/_authed/admin/tricks/create': typeof AuthedAdminTricksCreateRoute
  '/_authed/admin/tricks/modifiers': typeof AuthedAdminTricksModifiersRoute
  '/_authed/auth/me/edit': typeof AuthedAuthMeEditRoute
  '/_authed/posts/$postId/edit': typeof AuthedPostsPostIdEditRoute
  '/_authed/tricks/$trickId/submit-video': typeof AuthedTricksTrickIdSubmitVideoRoute
  '/_authed/tricks/$trickId/suggest': typeof AuthedTricksTrickIdSuggestRoute
  '/_authed/auth/me/': typeof AuthedAuthMeIndexRoute
  '/games/rius/previous/': typeof GamesRiusPreviousIndexRoute
  '/games/rius/upcoming/': typeof GamesRiusUpcomingIndexRoute
  '/_authed/admin/tricks/$trickId/edit': typeof AuthedAdminTricksTrickIdEditRoute
  '/_authed/admin/tricks/$trickId/videos': typeof AuthedAdminTricksTrickIdVideosRoute
  '/_authed/admin/tricks/elements/create': typeof AuthedAdminTricksElementsCreateRoute
  '/_authed/games/rius/upcoming/join': typeof AuthedGamesRiusUpcomingJoinRoute
  '/_authed/admin/tricks/elements/': typeof AuthedAdminTricksElementsIndexRoute
  '/_authed/tricks/submissions/$submissionId/': typeof AuthedTricksSubmissionsSubmissionIdIndexRoute
  '/_authed/tricks/suggestions/$suggestionId/': typeof AuthedTricksSuggestionsSuggestionIdIndexRoute
  '/games/bius/sets/$setId/': typeof GamesBiusSetsSetIdIndexRoute
  '/games/rius/sets/$setId/': typeof GamesRiusSetsSetIdIndexRoute
  '/games/rius/submissions/$submissionId/': typeof GamesRiusSubmissionsSubmissionIdIndexRoute
  '/games/sius/stacks/$stackId/': typeof GamesSiusStacksStackIdIndexRoute
  '/_authed/admin/tricks/elements/$elementId/edit': typeof AuthedAdminTricksElementsElementIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/bius'
    | '/games/rius'
    | '/games/sius'
    | '/admin'
    | '/feedback'
    | '/auth/register'
    | '/stats/contributors'
    | '/tricks/$trickId'
    | '/users/$userId'
    | '/chat'
    | '/games'
    | '/map'
    | '/posts'
    | '/stats'
    | '/tricks'
    | '/users'
    | '/vault'
    | '/notifications/settings'
    | '/posts/create'
    | '/tricks/review'
    | '/tricks/submit'
    | '/api/mux/webhook'
    | '/auth/code/send'
    | '/auth/code/verify'
    | '/games/bius/start'
    | '/games/rius/active'
    | '/games/sius/start'
    | '/vault/valut/bak'
    | '/notifications'
    | '/games/bius/'
    | '/games/sius/'
    | '/posts/$postId'
    | '/vault/$videoId'
    | '/admin/tricks/create'
    | '/admin/tricks/modifiers'
    | '/auth/me/edit'
    | '/posts/$postId/edit'
    | '/tricks/$trickId/submit-video'
    | '/tricks/$trickId/suggest'
    | '/auth/me'
    | '/games/rius/previous'
    | '/games/rius/upcoming'
    | '/admin/tricks/$trickId/edit'
    | '/admin/tricks/$trickId/videos'
    | '/admin/tricks/elements/create'
    | '/games/rius/upcoming/join'
    | '/admin/tricks/elements'
    | '/tricks/submissions/$submissionId'
    | '/tricks/suggestions/$suggestionId'
    | '/games/bius/sets/$setId'
    | '/games/rius/sets/$setId'
    | '/games/rius/submissions/$submissionId'
    | '/games/sius/stacks/$stackId'
    | '/admin/tricks/elements/$elementId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/rius'
    | '/admin'
    | '/feedback'
    | '/auth/register'
    | '/stats/contributors'
    | '/tricks/$trickId'
    | '/users/$userId'
    | '/chat'
    | '/games'
    | '/map'
    | '/posts'
    | '/stats'
    | '/tricks'
    | '/users'
    | '/vault'
    | '/notifications/settings'
    | '/posts/create'
    | '/tricks/review'
    | '/tricks/submit'
    | '/api/mux/webhook'
    | '/auth/code/send'
    | '/auth/code/verify'
    | '/games/bius/start'
    | '/games/rius/active'
    | '/games/sius/start'
    | '/vault/valut/bak'
    | '/notifications'
    | '/games/bius'
    | '/games/sius'
    | '/posts/$postId'
    | '/vault/$videoId'
    | '/admin/tricks/create'
    | '/admin/tricks/modifiers'
    | '/auth/me/edit'
    | '/posts/$postId/edit'
    | '/tricks/$trickId/submit-video'
    | '/tricks/$trickId/suggest'
    | '/auth/me'
    | '/games/rius/previous'
    | '/games/rius/upcoming'
    | '/admin/tricks/$trickId/edit'
    | '/admin/tricks/$trickId/videos'
    | '/admin/tricks/elements/create'
    | '/games/rius/upcoming/join'
    | '/admin/tricks/elements'
    | '/tricks/submissions/$submissionId'
    | '/tricks/suggestions/$suggestionId'
    | '/games/bius/sets/$setId'
    | '/games/rius/sets/$setId'
    | '/games/rius/submissions/$submissionId'
    | '/games/sius/stacks/$stackId'
    | '/admin/tricks/elements/$elementId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/games/bius'
    | '/games/rius'
    | '/games/sius'
    | '/_authed/admin'
    | '/_authed/feedback'
    | '/auth/register'
    | '/stats/contributors'
    | '/tricks/$trickId'
    | '/users/$userId'
    | '/chat/'
    | '/games/'
    | '/map/'
    | '/posts/'
    | '/stats/'
    | '/tricks/'
    | '/users/'
    | '/vault/'
    | '/_authed/notifications/settings'
    | '/_authed/posts/create'
    | '/_authed/tricks/review'
    | '/_authed/tricks/submit'
    | '/api/mux/webhook'
    | '/auth/code/send'
    | '/auth/code/verify'
    | '/games/bius/start'
    | '/games/rius/active'
    | '/games/sius/start'
    | '/vault/valut/bak'
    | '/_authed/notifications/'
    | '/games/bius/'
    | '/games/sius/'
    | '/posts/$postId/'
    | '/vault/$videoId/'
    | '/_authed/admin/tricks/create'
    | '/_authed/admin/tricks/modifiers'
    | '/_authed/auth/me/edit'
    | '/_authed/posts/$postId/edit'
    | '/_authed/tricks/$trickId/submit-video'
    | '/_authed/tricks/$trickId/suggest'
    | '/_authed/auth/me/'
    | '/games/rius/previous/'
    | '/games/rius/upcoming/'
    | '/_authed/admin/tricks/$trickId/edit'
    | '/_authed/admin/tricks/$trickId/videos'
    | '/_authed/admin/tricks/elements/create'
    | '/_authed/games/rius/upcoming/join'
    | '/_authed/admin/tricks/elements/'
    | '/_authed/tricks/submissions/$submissionId/'
    | '/_authed/tricks/suggestions/$suggestionId/'
    | '/games/bius/sets/$setId/'
    | '/games/rius/sets/$setId/'
    | '/games/rius/submissions/$submissionId/'
    | '/games/sius/stacks/$stackId/'
    | '/_authed/admin/tricks/elements/$elementId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  GamesBiusRouteRoute: typeof GamesBiusRouteRouteWithChildren
  GamesRiusRouteRoute: typeof GamesRiusRouteRouteWithChildren
  GamesSiusRouteRoute: typeof GamesSiusRouteRouteWithChildren
  AuthRegisterRoute: typeof AuthRegisterRoute
  StatsContributorsRoute: typeof StatsContributorsRoute
  TricksTrickIdRoute: typeof TricksTrickIdRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  MapIndexRoute: typeof MapIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  TricksIndexRoute: typeof TricksIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  VaultIndexRoute: typeof VaultIndexRoute
  ApiMuxWebhookRoute: typeof ApiMuxWebhookRoute
  AuthCodeSendRoute: typeof AuthCodeSendRoute
  AuthCodeVerifyRoute: typeof AuthCodeVerifyRoute
  VaultValutBakRoute: typeof VaultValutBakRoute
  PostsPostIdIndexRoute: typeof PostsPostIdIndexRoute
  VaultVideoIdIndexRoute: typeof VaultVideoIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/': {
      id: '/vault/'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tricks/': {
      id: '/tricks/'
      path: '/tricks'
      fullPath: '/tricks'
      preLoaderRoute: typeof TricksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tricks/$trickId': {
      id: '/tricks/$trickId'
      path: '/tricks/$trickId'
      fullPath: '/tricks/$trickId'
      preLoaderRoute: typeof TricksTrickIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/contributors': {
      id: '/stats/contributors'
      path: '/stats/contributors'
      fullPath: '/stats/contributors'
      preLoaderRoute: typeof StatsContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/feedback': {
      id: '/_authed/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthedFeedbackRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/games/sius': {
      id: '/games/sius'
      path: '/games/sius'
      fullPath: '/games/sius'
      preLoaderRoute: typeof GamesSiusRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/rius': {
      id: '/games/rius'
      path: '/games/rius'
      fullPath: '/games/rius'
      preLoaderRoute: typeof GamesRiusRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/bius': {
      id: '/games/bius'
      path: '/games/bius'
      fullPath: '/games/bius'
      preLoaderRoute: typeof GamesBiusRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$videoId/': {
      id: '/vault/$videoId/'
      path: '/vault/$videoId'
      fullPath: '/vault/$videoId'
      preLoaderRoute: typeof VaultVideoIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId/': {
      id: '/posts/$postId/'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/sius/': {
      id: '/games/sius/'
      path: '/'
      fullPath: '/games/sius/'
      preLoaderRoute: typeof GamesSiusIndexRouteImport
      parentRoute: typeof GamesSiusRouteRoute
    }
    '/games/bius/': {
      id: '/games/bius/'
      path: '/'
      fullPath: '/games/bius/'
      preLoaderRoute: typeof GamesBiusIndexRouteImport
      parentRoute: typeof GamesBiusRouteRoute
    }
    '/_authed/notifications/': {
      id: '/_authed/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/vault/valut/bak': {
      id: '/vault/valut/bak'
      path: '/vault/valut/bak'
      fullPath: '/vault/valut/bak'
      preLoaderRoute: typeof VaultValutBakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/sius/start': {
      id: '/games/sius/start'
      path: '/start'
      fullPath: '/games/sius/start'
      preLoaderRoute: typeof GamesSiusStartRouteImport
      parentRoute: typeof GamesSiusRouteRoute
    }
    '/games/rius/active': {
      id: '/games/rius/active'
      path: '/active'
      fullPath: '/games/rius/active'
      preLoaderRoute: typeof GamesRiusActiveRouteImport
      parentRoute: typeof GamesRiusRouteRoute
    }
    '/games/bius/start': {
      id: '/games/bius/start'
      path: '/start'
      fullPath: '/games/bius/start'
      preLoaderRoute: typeof GamesBiusStartRouteImport
      parentRoute: typeof GamesBiusRouteRoute
    }
    '/auth/code/verify': {
      id: '/auth/code/verify'
      path: '/auth/code/verify'
      fullPath: '/auth/code/verify'
      preLoaderRoute: typeof AuthCodeVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/code/send': {
      id: '/auth/code/send'
      path: '/auth/code/send'
      fullPath: '/auth/code/send'
      preLoaderRoute: typeof AuthCodeSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mux/webhook': {
      id: '/api/mux/webhook'
      path: '/api/mux/webhook'
      fullPath: '/api/mux/webhook'
      preLoaderRoute: typeof ApiMuxWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/tricks/submit': {
      id: '/_authed/tricks/submit'
      path: '/tricks/submit'
      fullPath: '/tricks/submit'
      preLoaderRoute: typeof AuthedTricksSubmitRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tricks/review': {
      id: '/_authed/tricks/review'
      path: '/tricks/review'
      fullPath: '/tricks/review'
      preLoaderRoute: typeof AuthedTricksReviewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/create': {
      id: '/_authed/posts/create'
      path: '/posts/create'
      fullPath: '/posts/create'
      preLoaderRoute: typeof AuthedPostsCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications/settings': {
      id: '/_authed/notifications/settings'
      path: '/notifications/settings'
      fullPath: '/notifications/settings'
      preLoaderRoute: typeof AuthedNotificationsSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/games/rius/upcoming/': {
      id: '/games/rius/upcoming/'
      path: '/upcoming'
      fullPath: '/games/rius/upcoming'
      preLoaderRoute: typeof GamesRiusUpcomingIndexRouteImport
      parentRoute: typeof GamesRiusRouteRoute
    }
    '/games/rius/previous/': {
      id: '/games/rius/previous/'
      path: '/previous'
      fullPath: '/games/rius/previous'
      preLoaderRoute: typeof GamesRiusPreviousIndexRouteImport
      parentRoute: typeof GamesRiusRouteRoute
    }
    '/_authed/auth/me/': {
      id: '/_authed/auth/me/'
      path: '/auth/me'
      fullPath: '/auth/me'
      preLoaderRoute: typeof AuthedAuthMeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tricks/$trickId/suggest': {
      id: '/_authed/tricks/$trickId/suggest'
      path: '/tricks/$trickId/suggest'
      fullPath: '/tricks/$trickId/suggest'
      preLoaderRoute: typeof AuthedTricksTrickIdSuggestRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tricks/$trickId/submit-video': {
      id: '/_authed/tricks/$trickId/submit-video'
      path: '/tricks/$trickId/submit-video'
      fullPath: '/tricks/$trickId/submit-video'
      preLoaderRoute: typeof AuthedTricksTrickIdSubmitVideoRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/$postId/edit': {
      id: '/_authed/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof AuthedPostsPostIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/auth/me/edit': {
      id: '/_authed/auth/me/edit'
      path: '/auth/me/edit'
      fullPath: '/auth/me/edit'
      preLoaderRoute: typeof AuthedAuthMeEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/tricks/modifiers': {
      id: '/_authed/admin/tricks/modifiers'
      path: '/tricks/modifiers'
      fullPath: '/admin/tricks/modifiers'
      preLoaderRoute: typeof AuthedAdminTricksModifiersRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/tricks/create': {
      id: '/_authed/admin/tricks/create'
      path: '/tricks/create'
      fullPath: '/admin/tricks/create'
      preLoaderRoute: typeof AuthedAdminTricksCreateRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/games/sius/stacks/$stackId/': {
      id: '/games/sius/stacks/$stackId/'
      path: '/stacks/$stackId'
      fullPath: '/games/sius/stacks/$stackId'
      preLoaderRoute: typeof GamesSiusStacksStackIdIndexRouteImport
      parentRoute: typeof GamesSiusRouteRoute
    }
    '/games/rius/submissions/$submissionId/': {
      id: '/games/rius/submissions/$submissionId/'
      path: '/submissions/$submissionId'
      fullPath: '/games/rius/submissions/$submissionId'
      preLoaderRoute: typeof GamesRiusSubmissionsSubmissionIdIndexRouteImport
      parentRoute: typeof GamesRiusRouteRoute
    }
    '/games/rius/sets/$setId/': {
      id: '/games/rius/sets/$setId/'
      path: '/sets/$setId'
      fullPath: '/games/rius/sets/$setId'
      preLoaderRoute: typeof GamesRiusSetsSetIdIndexRouteImport
      parentRoute: typeof GamesRiusRouteRoute
    }
    '/games/bius/sets/$setId/': {
      id: '/games/bius/sets/$setId/'
      path: '/sets/$setId'
      fullPath: '/games/bius/sets/$setId'
      preLoaderRoute: typeof GamesBiusSetsSetIdIndexRouteImport
      parentRoute: typeof GamesBiusRouteRoute
    }
    '/_authed/tricks/suggestions/$suggestionId/': {
      id: '/_authed/tricks/suggestions/$suggestionId/'
      path: '/tricks/suggestions/$suggestionId'
      fullPath: '/tricks/suggestions/$suggestionId'
      preLoaderRoute: typeof AuthedTricksSuggestionsSuggestionIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tricks/submissions/$submissionId/': {
      id: '/_authed/tricks/submissions/$submissionId/'
      path: '/tricks/submissions/$submissionId'
      fullPath: '/tricks/submissions/$submissionId'
      preLoaderRoute: typeof AuthedTricksSubmissionsSubmissionIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/tricks/elements/': {
      id: '/_authed/admin/tricks/elements/'
      path: '/tricks/elements'
      fullPath: '/admin/tricks/elements'
      preLoaderRoute: typeof AuthedAdminTricksElementsIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/games/rius/upcoming/join': {
      id: '/_authed/games/rius/upcoming/join'
      path: '/games/rius/upcoming/join'
      fullPath: '/games/rius/upcoming/join'
      preLoaderRoute: typeof AuthedGamesRiusUpcomingJoinRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/tricks/elements/create': {
      id: '/_authed/admin/tricks/elements/create'
      path: '/tricks/elements/create'
      fullPath: '/admin/tricks/elements/create'
      preLoaderRoute: typeof AuthedAdminTricksElementsCreateRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/tricks/$trickId/videos': {
      id: '/_authed/admin/tricks/$trickId/videos'
      path: '/tricks/$trickId/videos'
      fullPath: '/admin/tricks/$trickId/videos'
      preLoaderRoute: typeof AuthedAdminTricksTrickIdVideosRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/tricks/$trickId/edit': {
      id: '/_authed/admin/tricks/$trickId/edit'
      path: '/tricks/$trickId/edit'
      fullPath: '/admin/tricks/$trickId/edit'
      preLoaderRoute: typeof AuthedAdminTricksTrickIdEditRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/tricks/elements/$elementId/edit': {
      id: '/_authed/admin/tricks/elements/$elementId/edit'
      path: '/tricks/elements/$elementId/edit'
      fullPath: '/admin/tricks/elements/$elementId/edit'
      preLoaderRoute: typeof AuthedAdminTricksElementsElementIdEditRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminTricksCreateRoute: typeof AuthedAdminTricksCreateRoute
  AuthedAdminTricksModifiersRoute: typeof AuthedAdminTricksModifiersRoute
  AuthedAdminTricksTrickIdEditRoute: typeof AuthedAdminTricksTrickIdEditRoute
  AuthedAdminTricksTrickIdVideosRoute: typeof AuthedAdminTricksTrickIdVideosRoute
  AuthedAdminTricksElementsCreateRoute: typeof AuthedAdminTricksElementsCreateRoute
  AuthedAdminTricksElementsIndexRoute: typeof AuthedAdminTricksElementsIndexRoute
  AuthedAdminTricksElementsElementIdEditRoute: typeof AuthedAdminTricksElementsElementIdEditRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminTricksCreateRoute: AuthedAdminTricksCreateRoute,
  AuthedAdminTricksModifiersRoute: AuthedAdminTricksModifiersRoute,
  AuthedAdminTricksTrickIdEditRoute: AuthedAdminTricksTrickIdEditRoute,
  AuthedAdminTricksTrickIdVideosRoute: AuthedAdminTricksTrickIdVideosRoute,
  AuthedAdminTricksElementsCreateRoute: AuthedAdminTricksElementsCreateRoute,
  AuthedAdminTricksElementsIndexRoute: AuthedAdminTricksElementsIndexRoute,
  AuthedAdminTricksElementsElementIdEditRoute:
    AuthedAdminTricksElementsElementIdEditRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedFeedbackRoute: typeof AuthedFeedbackRoute
  AuthedNotificationsSettingsRoute: typeof AuthedNotificationsSettingsRoute
  AuthedPostsCreateRoute: typeof AuthedPostsCreateRoute
  AuthedTricksReviewRoute: typeof AuthedTricksReviewRoute
  AuthedTricksSubmitRoute: typeof AuthedTricksSubmitRoute
  AuthedNotificationsIndexRoute: typeof AuthedNotificationsIndexRoute
  AuthedAuthMeEditRoute: typeof AuthedAuthMeEditRoute
  AuthedPostsPostIdEditRoute: typeof AuthedPostsPostIdEditRoute
  AuthedTricksTrickIdSubmitVideoRoute: typeof AuthedTricksTrickIdSubmitVideoRoute
  AuthedTricksTrickIdSuggestRoute: typeof AuthedTricksTrickIdSuggestRoute
  AuthedAuthMeIndexRoute: typeof AuthedAuthMeIndexRoute
  AuthedGamesRiusUpcomingJoinRoute: typeof AuthedGamesRiusUpcomingJoinRoute
  AuthedTricksSubmissionsSubmissionIdIndexRoute: typeof AuthedTricksSubmissionsSubmissionIdIndexRoute
  AuthedTricksSuggestionsSuggestionIdIndexRoute: typeof AuthedTricksSuggestionsSuggestionIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedFeedbackRoute: AuthedFeedbackRoute,
  AuthedNotificationsSettingsRoute: AuthedNotificationsSettingsRoute,
  AuthedPostsCreateRoute: AuthedPostsCreateRoute,
  AuthedTricksReviewRoute: AuthedTricksReviewRoute,
  AuthedTricksSubmitRoute: AuthedTricksSubmitRoute,
  AuthedNotificationsIndexRoute: AuthedNotificationsIndexRoute,
  AuthedAuthMeEditRoute: AuthedAuthMeEditRoute,
  AuthedPostsPostIdEditRoute: AuthedPostsPostIdEditRoute,
  AuthedTricksTrickIdSubmitVideoRoute: AuthedTricksTrickIdSubmitVideoRoute,
  AuthedTricksTrickIdSuggestRoute: AuthedTricksTrickIdSuggestRoute,
  AuthedAuthMeIndexRoute: AuthedAuthMeIndexRoute,
  AuthedGamesRiusUpcomingJoinRoute: AuthedGamesRiusUpcomingJoinRoute,
  AuthedTricksSubmissionsSubmissionIdIndexRoute:
    AuthedTricksSubmissionsSubmissionIdIndexRoute,
  AuthedTricksSuggestionsSuggestionIdIndexRoute:
    AuthedTricksSuggestionsSuggestionIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface GamesBiusRouteRouteChildren {
  GamesBiusStartRoute: typeof GamesBiusStartRoute
  GamesBiusIndexRoute: typeof GamesBiusIndexRoute
  GamesBiusSetsSetIdIndexRoute: typeof GamesBiusSetsSetIdIndexRoute
}

const GamesBiusRouteRouteChildren: GamesBiusRouteRouteChildren = {
  GamesBiusStartRoute: GamesBiusStartRoute,
  GamesBiusIndexRoute: GamesBiusIndexRoute,
  GamesBiusSetsSetIdIndexRoute: GamesBiusSetsSetIdIndexRoute,
}

const GamesBiusRouteRouteWithChildren = GamesBiusRouteRoute._addFileChildren(
  GamesBiusRouteRouteChildren,
)

interface GamesRiusRouteRouteChildren {
  GamesRiusActiveRoute: typeof GamesRiusActiveRoute
  GamesRiusPreviousIndexRoute: typeof GamesRiusPreviousIndexRoute
  GamesRiusUpcomingIndexRoute: typeof GamesRiusUpcomingIndexRoute
  GamesRiusSetsSetIdIndexRoute: typeof GamesRiusSetsSetIdIndexRoute
  GamesRiusSubmissionsSubmissionIdIndexRoute: typeof GamesRiusSubmissionsSubmissionIdIndexRoute
}

const GamesRiusRouteRouteChildren: GamesRiusRouteRouteChildren = {
  GamesRiusActiveRoute: GamesRiusActiveRoute,
  GamesRiusPreviousIndexRoute: GamesRiusPreviousIndexRoute,
  GamesRiusUpcomingIndexRoute: GamesRiusUpcomingIndexRoute,
  GamesRiusSetsSetIdIndexRoute: GamesRiusSetsSetIdIndexRoute,
  GamesRiusSubmissionsSubmissionIdIndexRoute:
    GamesRiusSubmissionsSubmissionIdIndexRoute,
}

const GamesRiusRouteRouteWithChildren = GamesRiusRouteRoute._addFileChildren(
  GamesRiusRouteRouteChildren,
)

interface GamesSiusRouteRouteChildren {
  GamesSiusStartRoute: typeof GamesSiusStartRoute
  GamesSiusIndexRoute: typeof GamesSiusIndexRoute
  GamesSiusStacksStackIdIndexRoute: typeof GamesSiusStacksStackIdIndexRoute
}

const GamesSiusRouteRouteChildren: GamesSiusRouteRouteChildren = {
  GamesSiusStartRoute: GamesSiusStartRoute,
  GamesSiusIndexRoute: GamesSiusIndexRoute,
  GamesSiusStacksStackIdIndexRoute: GamesSiusStacksStackIdIndexRoute,
}

const GamesSiusRouteRouteWithChildren = GamesSiusRouteRoute._addFileChildren(
  GamesSiusRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  GamesBiusRouteRoute: GamesBiusRouteRouteWithChildren,
  GamesRiusRouteRoute: GamesRiusRouteRouteWithChildren,
  GamesSiusRouteRoute: GamesSiusRouteRouteWithChildren,
  AuthRegisterRoute: AuthRegisterRoute,
  StatsContributorsRoute: StatsContributorsRoute,
  TricksTrickIdRoute: TricksTrickIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  MapIndexRoute: MapIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  TricksIndexRoute: TricksIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  VaultIndexRoute: VaultIndexRoute,
  ApiMuxWebhookRoute: ApiMuxWebhookRoute,
  AuthCodeSendRoute: AuthCodeSendRoute,
  AuthCodeVerifyRoute: AuthCodeVerifyRoute,
  VaultValutBakRoute: VaultValutBakRoute,
  PostsPostIdIndexRoute: PostsPostIdIndexRoute,
  VaultVideoIdIndexRoute: VaultVideoIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
