/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as GamesRiusRouteRouteImport } from './routes/games/rius/route'
import { Route as PostsPostIdIndexRouteImport } from './routes/posts/$postId/index'
import { Route as GamesRiusActiveRouteImport } from './routes/games/rius/active'
import { Route as AuthedPostsCreateRouteImport } from './routes/_authed/posts/create'
import { Route as GamesRiusUpcomingIndexRouteImport } from './routes/games/rius/upcoming/index'
import { Route as GamesRiusPreviousIndexRouteImport } from './routes/games/rius/previous/index'
import { Route as AuthedAuthMeIndexRouteImport } from './routes/_authed/auth/me/index'
import { Route as AuthedPostsPostIdEditRouteImport } from './routes/_authed/posts/$postId/edit'
import { Route as AuthedAuthMeEditRouteImport } from './routes/_authed/auth/me/edit'
import { Route as GamesRiusSetsSetIdIndexRouteImport } from './routes/games/rius/sets/$setId/index'
import { Route as AuthedGamesRiusUpcomingJoinRouteImport } from './routes/_authed/games/rius/upcoming/join'
import { ServerRoute as ApiMuxWebhookServerRouteImport } from './routes/api/mux/webhook'
import { ServerRoute as ApiMuxUrlServerRouteImport } from './routes/api/mux/url'
import { ServerRoute as ApiAuthVerifyServerRouteImport } from './routes/api/auth/verify'

const rootServerRouteImport = createServerRootRoute()

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRiusRouteRoute = GamesRiusRouteRouteImport.update({
  id: '/games/rius',
  path: '/games/rius',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdIndexRoute = PostsPostIdIndexRouteImport.update({
  id: '/posts/$postId/',
  path: '/posts/$postId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRiusActiveRoute = GamesRiusActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => GamesRiusRouteRoute,
} as any)
const AuthedPostsCreateRoute = AuthedPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => AuthedRoute,
} as any)
const GamesRiusUpcomingIndexRoute = GamesRiusUpcomingIndexRouteImport.update({
  id: '/upcoming/',
  path: '/upcoming/',
  getParentRoute: () => GamesRiusRouteRoute,
} as any)
const GamesRiusPreviousIndexRoute = GamesRiusPreviousIndexRouteImport.update({
  id: '/previous/',
  path: '/previous/',
  getParentRoute: () => GamesRiusRouteRoute,
} as any)
const AuthedAuthMeIndexRoute = AuthedAuthMeIndexRouteImport.update({
  id: '/auth/me/',
  path: '/auth/me/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsPostIdEditRoute = AuthedPostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuthMeEditRoute = AuthedAuthMeEditRouteImport.update({
  id: '/auth/me/edit',
  path: '/auth/me/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const GamesRiusSetsSetIdIndexRoute = GamesRiusSetsSetIdIndexRouteImport.update({
  id: '/sets/$setId/',
  path: '/sets/$setId/',
  getParentRoute: () => GamesRiusRouteRoute,
} as any)
const AuthedGamesRiusUpcomingJoinRoute =
  AuthedGamesRiusUpcomingJoinRouteImport.update({
    id: '/games/rius/upcoming/join',
    path: '/games/rius/upcoming/join',
    getParentRoute: () => AuthedRoute,
  } as any)
const ApiMuxWebhookServerRoute = ApiMuxWebhookServerRouteImport.update({
  id: '/api/mux/webhook',
  path: '/api/mux/webhook',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMuxUrlServerRoute = ApiMuxUrlServerRouteImport.update({
  id: '/api/mux/url',
  path: '/api/mux/url',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthVerifyServerRoute = ApiAuthVerifyServerRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/games/rius': typeof GamesRiusRouteRouteWithChildren
  '/users/$userId': typeof UsersUserIdRoute
  '/chat': typeof ChatIndexRoute
  '/posts': typeof PostsIndexRoute
  '/users': typeof UsersIndexRoute
  '/posts/create': typeof AuthedPostsCreateRoute
  '/games/rius/active': typeof GamesRiusActiveRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
  '/auth/me/edit': typeof AuthedAuthMeEditRoute
  '/posts/$postId/edit': typeof AuthedPostsPostIdEditRoute
  '/auth/me': typeof AuthedAuthMeIndexRoute
  '/games/rius/previous': typeof GamesRiusPreviousIndexRoute
  '/games/rius/upcoming': typeof GamesRiusUpcomingIndexRoute
  '/games/rius/upcoming/join': typeof AuthedGamesRiusUpcomingJoinRoute
  '/games/rius/sets/$setId': typeof GamesRiusSetsSetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/games/rius': typeof GamesRiusRouteRouteWithChildren
  '/users/$userId': typeof UsersUserIdRoute
  '/chat': typeof ChatIndexRoute
  '/posts': typeof PostsIndexRoute
  '/users': typeof UsersIndexRoute
  '/posts/create': typeof AuthedPostsCreateRoute
  '/games/rius/active': typeof GamesRiusActiveRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
  '/auth/me/edit': typeof AuthedAuthMeEditRoute
  '/posts/$postId/edit': typeof AuthedPostsPostIdEditRoute
  '/auth/me': typeof AuthedAuthMeIndexRoute
  '/games/rius/previous': typeof GamesRiusPreviousIndexRoute
  '/games/rius/upcoming': typeof GamesRiusUpcomingIndexRoute
  '/games/rius/upcoming/join': typeof AuthedGamesRiusUpcomingJoinRoute
  '/games/rius/sets/$setId': typeof GamesRiusSetsSetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRoute
  '/games/rius': typeof GamesRiusRouteRouteWithChildren
  '/users/$userId': typeof UsersUserIdRoute
  '/chat/': typeof ChatIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/_authed/posts/create': typeof AuthedPostsCreateRoute
  '/games/rius/active': typeof GamesRiusActiveRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
  '/_authed/auth/me/edit': typeof AuthedAuthMeEditRoute
  '/_authed/posts/$postId/edit': typeof AuthedPostsPostIdEditRoute
  '/_authed/auth/me/': typeof AuthedAuthMeIndexRoute
  '/games/rius/previous/': typeof GamesRiusPreviousIndexRoute
  '/games/rius/upcoming/': typeof GamesRiusUpcomingIndexRoute
  '/_authed/games/rius/upcoming/join': typeof AuthedGamesRiusUpcomingJoinRoute
  '/games/rius/sets/$setId/': typeof GamesRiusSetsSetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/games/rius'
    | '/users/$userId'
    | '/chat'
    | '/posts'
    | '/users'
    | '/posts/create'
    | '/games/rius/active'
    | '/posts/$postId'
    | '/auth/me/edit'
    | '/posts/$postId/edit'
    | '/auth/me'
    | '/games/rius/previous'
    | '/games/rius/upcoming'
    | '/games/rius/upcoming/join'
    | '/games/rius/sets/$setId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/games/rius'
    | '/users/$userId'
    | '/chat'
    | '/posts'
    | '/users'
    | '/posts/create'
    | '/games/rius/active'
    | '/posts/$postId'
    | '/auth/me/edit'
    | '/posts/$postId/edit'
    | '/auth/me'
    | '/games/rius/previous'
    | '/games/rius/upcoming'
    | '/games/rius/upcoming/join'
    | '/games/rius/sets/$setId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth'
    | '/games/rius'
    | '/users/$userId'
    | '/chat/'
    | '/posts/'
    | '/users/'
    | '/_authed/posts/create'
    | '/games/rius/active'
    | '/posts/$postId/'
    | '/_authed/auth/me/edit'
    | '/_authed/posts/$postId/edit'
    | '/_authed/auth/me/'
    | '/games/rius/previous/'
    | '/games/rius/upcoming/'
    | '/_authed/games/rius/upcoming/join'
    | '/games/rius/sets/$setId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRoute
  GamesRiusRouteRoute: typeof GamesRiusRouteRouteWithChildren
  UsersUserIdRoute: typeof UsersUserIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  PostsPostIdIndexRoute: typeof PostsPostIdIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/verify': typeof ApiAuthVerifyServerRoute
  '/api/mux/url': typeof ApiMuxUrlServerRoute
  '/api/mux/webhook': typeof ApiMuxWebhookServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/verify': typeof ApiAuthVerifyServerRoute
  '/api/mux/url': typeof ApiMuxUrlServerRoute
  '/api/mux/webhook': typeof ApiMuxWebhookServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/verify': typeof ApiAuthVerifyServerRoute
  '/api/mux/url': typeof ApiMuxUrlServerRoute
  '/api/mux/webhook': typeof ApiMuxWebhookServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/verify' | '/api/mux/url' | '/api/mux/webhook'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/verify' | '/api/mux/url' | '/api/mux/webhook'
  id: '__root__' | '/api/auth/verify' | '/api/mux/url' | '/api/mux/webhook'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthVerifyServerRoute: typeof ApiAuthVerifyServerRoute
  ApiMuxUrlServerRoute: typeof ApiMuxUrlServerRoute
  ApiMuxWebhookServerRoute: typeof ApiMuxWebhookServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/rius': {
      id: '/games/rius'
      path: '/games/rius'
      fullPath: '/games/rius'
      preLoaderRoute: typeof GamesRiusRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId/': {
      id: '/posts/$postId/'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/rius/active': {
      id: '/games/rius/active'
      path: '/active'
      fullPath: '/games/rius/active'
      preLoaderRoute: typeof GamesRiusActiveRouteImport
      parentRoute: typeof GamesRiusRouteRoute
    }
    '/_authed/posts/create': {
      id: '/_authed/posts/create'
      path: '/posts/create'
      fullPath: '/posts/create'
      preLoaderRoute: typeof AuthedPostsCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/games/rius/upcoming/': {
      id: '/games/rius/upcoming/'
      path: '/upcoming'
      fullPath: '/games/rius/upcoming'
      preLoaderRoute: typeof GamesRiusUpcomingIndexRouteImport
      parentRoute: typeof GamesRiusRouteRoute
    }
    '/games/rius/previous/': {
      id: '/games/rius/previous/'
      path: '/previous'
      fullPath: '/games/rius/previous'
      preLoaderRoute: typeof GamesRiusPreviousIndexRouteImport
      parentRoute: typeof GamesRiusRouteRoute
    }
    '/_authed/auth/me/': {
      id: '/_authed/auth/me/'
      path: '/auth/me'
      fullPath: '/auth/me'
      preLoaderRoute: typeof AuthedAuthMeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/$postId/edit': {
      id: '/_authed/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof AuthedPostsPostIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/auth/me/edit': {
      id: '/_authed/auth/me/edit'
      path: '/auth/me/edit'
      fullPath: '/auth/me/edit'
      preLoaderRoute: typeof AuthedAuthMeEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/games/rius/sets/$setId/': {
      id: '/games/rius/sets/$setId/'
      path: '/sets/$setId'
      fullPath: '/games/rius/sets/$setId'
      preLoaderRoute: typeof GamesRiusSetsSetIdIndexRouteImport
      parentRoute: typeof GamesRiusRouteRoute
    }
    '/_authed/games/rius/upcoming/join': {
      id: '/_authed/games/rius/upcoming/join'
      path: '/games/rius/upcoming/join'
      fullPath: '/games/rius/upcoming/join'
      preLoaderRoute: typeof AuthedGamesRiusUpcomingJoinRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/mux/webhook': {
      id: '/api/mux/webhook'
      path: '/api/mux/webhook'
      fullPath: '/api/mux/webhook'
      preLoaderRoute: typeof ApiMuxWebhookServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/mux/url': {
      id: '/api/mux/url'
      path: '/api/mux/url'
      fullPath: '/api/mux/url'
      preLoaderRoute: typeof ApiMuxUrlServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedPostsCreateRoute: typeof AuthedPostsCreateRoute
  AuthedAuthMeEditRoute: typeof AuthedAuthMeEditRoute
  AuthedPostsPostIdEditRoute: typeof AuthedPostsPostIdEditRoute
  AuthedAuthMeIndexRoute: typeof AuthedAuthMeIndexRoute
  AuthedGamesRiusUpcomingJoinRoute: typeof AuthedGamesRiusUpcomingJoinRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPostsCreateRoute: AuthedPostsCreateRoute,
  AuthedAuthMeEditRoute: AuthedAuthMeEditRoute,
  AuthedPostsPostIdEditRoute: AuthedPostsPostIdEditRoute,
  AuthedAuthMeIndexRoute: AuthedAuthMeIndexRoute,
  AuthedGamesRiusUpcomingJoinRoute: AuthedGamesRiusUpcomingJoinRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface GamesRiusRouteRouteChildren {
  GamesRiusActiveRoute: typeof GamesRiusActiveRoute
  GamesRiusPreviousIndexRoute: typeof GamesRiusPreviousIndexRoute
  GamesRiusUpcomingIndexRoute: typeof GamesRiusUpcomingIndexRoute
  GamesRiusSetsSetIdIndexRoute: typeof GamesRiusSetsSetIdIndexRoute
}

const GamesRiusRouteRouteChildren: GamesRiusRouteRouteChildren = {
  GamesRiusActiveRoute: GamesRiusActiveRoute,
  GamesRiusPreviousIndexRoute: GamesRiusPreviousIndexRoute,
  GamesRiusUpcomingIndexRoute: GamesRiusUpcomingIndexRoute,
  GamesRiusSetsSetIdIndexRoute: GamesRiusSetsSetIdIndexRoute,
}

const GamesRiusRouteRouteWithChildren = GamesRiusRouteRoute._addFileChildren(
  GamesRiusRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRoute,
  GamesRiusRouteRoute: GamesRiusRouteRouteWithChildren,
  UsersUserIdRoute: UsersUserIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  PostsPostIdIndexRoute: PostsPostIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthVerifyServerRoute: ApiAuthVerifyServerRoute,
  ApiMuxUrlServerRoute: ApiMuxUrlServerRoute,
  ApiMuxWebhookServerRoute: ApiMuxWebhookServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
